Photon commander
CSE-WestHS/FRC2023Command-Based pull request #10
Opened 2023-02-07 23:42 UTC by superheropug

2023-02-07 23:57 UTC, Zandar-Double07 requested changes
Looks mostly good, just clean up a couple of things before we merge.

2023-02-07 23:57 UTC, Zandar-Double07 commented on src/main/java/frc/robot/Robot.java
> +  //public PhotonVisionManager photon;
Is this comment needed?

2023-02-07 23:57 UTC, Zandar-Double07 commented on src/main/java/frc/robot/RobotContainer.java
> +  private final DriveBackward DriveThreeRotoations = new DriveBackward(DriveSubsystem,3.0, 0.25 );
Keep the old turning commands, you can keep the new additions

2023-02-07 23:57 UTC, Zandar-Double07 commented on src/main/java/frc/robot/RobotContainer.java
> +  public PhotonVisionManager getPhoton(){
Can you explain what this is used for?

2023-02-08 00:16 UTC, Atika2022 approved these changes
The code seems fine and it works

2023-02-11 16:19 UTC, closed without merging